### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by lukas-schaetzle** [agentejo/Detektivo#10]
I've just tried out this addon with Cockpit 0.10.0 and it doesn't seem to work anymore. I used the tntsearch engine and did include a collection with fields to index in the config.yaml. I can also call the REST endpoint but it always just returns an empty array. 

config.yaml:
```
detektivo:
  engine: tntsearch

  collections:
    posts: [title, excerpt, content]
```
