### ISSUE TITLE
Trouble indexing/reindexing

### ISSUE THREAD

**Issue by emdahlstrom** [agentejo/Detektivo#9]
Hi! having some trouble indexing/reindexing on with the newest cockpit-next and newest detektivo. 

Regardless engine, the indexing spinner just keeps going and checking the network tab I can find the following response:
```
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>cockpit-next/addons/Detektivo/Storage/Algolia.php</b> on line <b>30</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>cockpit-next/addons/Detektivo/vendor/algolia/algoliasearch-client-php/src/AlgoliaSearch/Index.php</b> on line <b>1447</b><br />
{"finished":true,"imported":1}
```

I also get the following javascript error:
```
Uncaught (in promise) TypeError: Cannot read property 'imported' of null
    at <anonymous>:13:33
```

Any idea what this might be about?

It worked on a clean install but when I copied over my storage directory from production it broke. I'm just indexing simple text fields.

**Comment by emdahlstrom** [comment]
Exporting the content from prod and then importing it in the clean install solves the problem but it's unclear why prod stopped working

**Comment by jasonday** [comment]
I'm getting this issue as well (with algolia)

**Comment by jasonday** [comment]
Continues to be an issue:
![image](https://user-images.githubusercontent.com/748011/84431731-c778a380-abf9-11ea-9d6b-48447057e74c.png)

Config:
```
detektivo:
    collections:
        cat_ruleset: [ruleid, description]
        aria_properties: [aria_property, description]
        aria_states: [aria_state, description]
        aria_roles: [role, description]
        html_elements: [tag, description]
        roles: [role, description]
        standards: [name, description]
        substandards: [name, description]
```
